arcface:
  m: 0.5
  number_sub_center: 1
  s: 30.0
augmentation:
  cutmix_alpha: 1.0
  mixup_alpha: 0.2
  randaug_m: 9
  randaug_n: 2
  random_erasing_p: 0.25
  use_flip_tta: false
  use_randaug: true
base:
  batch_size: 64
  image_size: 384
  max_device_batch_size: 16
  num_classes: 400
  num_workers: 8
  seed: 42
model:
  name: efficientnet_b5
  pretrained_path: ./efficientnet_b5_numclasses_0.pth
normalize:
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
optimizer:
  base_learning_rate: 0.001
  total_epoch: 1
  warmup_epoch: 5
  weight_decay: 0.0001
paths:
  exp_name: exp_400
  output_dir: ./train_outputs
  resume: 
  train_dir: ./data/webfg400_train/train
  val_dir: ./data/webfg400_train/val
